export const SONGS_PATH = process.env.SONGS_PATH || "./public/songs"
export const GITHUB_REPOSITORY = process.env.GITHUB_REPOSITORY || "https://github.com/WeAreMahsaAmini"
export const BASE_SONGS_URL = process.env.BASE_SONGS_URL || "/songs"
export const APP_VERSION = process.env.APP_VERSION || ""
export const APP_URL = process.env.APP_URL || "localhost:3000"