export const SONGS_PATH = process.env.SONGS_PATH || "songs"
export const GITHUB_REPOSITORY = process.env.GITHUB_REPOSITORY || "https://github.com/IJustWantSomeFreedom/sync-mahsa"
export const APP_VERSION = process.env.APP_VERSION || ""
export const APP_URL = process.env.APP_URL || "localhost:3000"
export const CDN_URL = process.env.CDN_URL || "localhost:3000"